
version: '3.3'

services:

  mysql1:
    container_name: mysql1
    image: mysql:5.7.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
      MYSQL_DATABASE: hive