
version: '3.3'

services:

  bigdata-hadoop1:
    container_name: bigdata-hadoop1
    build:
      context: ./services/hadoop/2.7
    image: yinfuyuan/hadoop:2.7.6
    hostname: bigdata-hadoop1
    ports:
      - 9000:9000
      - 50070:50070
      - 8088:8088
      - 19888:19888
    environment:
      HADOOP_CLUSTER_MASTER: "true"
      HDFS_FS_DEFAULTFS: hdfs://bigdata-hadoop1:9000
      HDFS_SLAVES: bigdata-hadoop2,bigdata-hadoop3
      HDFS_DFS_NAMENODE_SECONDARY_HTTP_ADDRESS: bigdata-hadoop1:50090
      YARN_RESOURCEMANAGER_HOSTNAME: bigdata-hadoop1

  bigdata-hadoop2:
    container_name: bigdata-hadoop2
    build:
      context: ./services/hadoop/2.7
    image: yinfuyuan/hadoop:2.7.6
    hostname: bigdata-hadoop2
    environment:
      HDFS_FS_DEFAULTFS: hdfs://bigdata-hadoop1:9000
      HDFS_SLAVES: bigdata-hadoop2,bigdata-hadoop3
      HDFS_DFS_NAMENODE_SECONDARY_HTTP_ADDRESS: bigdata-hadoop1:50090
      YARN_RESOURCEMANAGER_HOSTNAME: bigdata-hadoop1

  bigdata-hadoop3:
    container_name: bigdata-hadoop3
    build:
      context: ./services/hadoop/2.7
    image: yinfuyuan/hadoop:2.7.6
    hostname: bigdata-hadoop3
    environment:
      HDFS_FS_DEFAULTFS: hdfs://bigdata-hadoop1:9000
      HDFS_SLAVES: bigdata-hadoop2,bigdata-hadoop3
      HDFS_DFS_NAMENODE_SECONDARY_HTTP_ADDRESS: bigdata-hadoop1:50090
      YARN_RESOURCEMANAGER_HOSTNAME: bigdata-hadoop1