
version: '3.3'

services:

  bigdata-hbase1:
    container_name: bigdata-hbase1
    build:
      context: ./services/hbase/2.0
    image: yinfuyuan/hbase:2.0.0
    hostname: bigdata-hbase1
    external_links:
      - bigdata-zookeeper1
      - bigdata-zookeeper2
      - bigdata-zookeeper3
    ports:
      - 16010:16010
    environment:
      HBASE_CLUSTER_MASTER: "true"
      HBASE_CLUSTER_DISTRIBUTED: "true"
      HBASE_ROOTDIR: hdfs://bigdata-hbase2:9000/hbase
      HBASE_BACKUP_MASTER: bigdata-hbase3
      HBASE_REGION_SERVERS: bigdata-hbase2,bigdata-hbase3
      HBASE_ZOOKEEPER_QUORUM: bigdata-zookeeper1,bigdata-zookeeper2,bigdata-zookeeper3
      HADOOP_CLUSTER_SLAVES: bigdata-hbase1,bigdata-hbase3
      HDFS_FS_DEFAULTFS: hdfs://bigdata-hbase2:9000
      HDFS_DFS_NAMENODE_SECONDARY_HTTP_ADDRESS: bigdata-hbase3:50090

  bigdata-hbase2:
    container_name: bigdata-hbase2
    build:
      context: ./services/hbase/2.0
    image: yinfuyuan/hbase:2.0.0
    hostname: bigdata-hbase2
    ports:
      - 50070:50070
    external_links:
      - bigdata-zookeeper1
      - bigdata-zookeeper2
      - bigdata-zookeeper3
    environment:
      HBASE_CLUSTER_DISTRIBUTED: "true"
      HBASE_ROOTDIR: hdfs://bigdata-hbase2:9000/hbase
      HBASE_BACKUP_MASTER: bigdata-hbase3
      HBASE_REGION_SERVERS: bigdata-hbase2,bigdata-hbase3
      HBASE_ZOOKEEPER_QUORUM: bigdata-zookeeper1,bigdata-zookeeper2,bigdata-zookeeper3
      HADOOP_CLUSTER_SLAVES: bigdata-hbase1,bigdata-hbase3
      HDFS_CLUSTER_MASTER: "true"
      HDFS_FS_DEFAULTFS: hdfs://bigdata-hbase2:9000
      HDFS_DFS_NAMENODE_SECONDARY_HTTP_ADDRESS: bigdata-hbase3:50090

  bigdata-hbase3:
    container_name: bigdata-hbase3
    build:
      context: ./services/hbase/2.0
    image: yinfuyuan/hbase:2.0.0
    hostname: bigdata-hbase3
    external_links:
      - bigdata-zookeeper1
      - bigdata-zookeeper2
      - bigdata-zookeeper3
    environment:
      HBASE_CLUSTER_DISTRIBUTED: "true"
      HBASE_ROOTDIR: hdfs://bigdata-hbase2:9000/hbase
      HBASE_BACKUP_MASTER: bigdata-hbase3
      HBASE_REGION_SERVERS: bigdata-hbase2,bigdata-hbase3
      HBASE_ZOOKEEPER_QUORUM: bigdata-zookeeper1,bigdata-zookeeper2,bigdata-zookeeper3
      HADOOP_CLUSTER_SLAVES: bigdata-hbase1,bigdata-hbase3
      HDFS_FS_DEFAULTFS: hdfs://bigdata-hbase2:9000
      HDFS_DFS_NAMENODE_SECONDARY_HTTP_ADDRESS: bigdata-hbase3:50090