
version: '3.3'

services:

  kafka1:
    container_name: kafka1
    build:
      context: ./services/kafka/1.1.0
    image: yinfuyuan/kafka:1.1.0-alpine
    hostname: kafka1
    ports:
      - 9092:9092
    external_links:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_CLUSTER: "true"
      BROKER_ID: 1
      LISTENERS: PLAINTEXT://kafka1:9092
      ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181

  kafka2:
    container_name: kafka2
    build:
      context: ./services/kafka/1.1.0
    image: yinfuyuan/kafka:1.1.0-alpine
    hostname: kafka2
    ports:
      - 9093:9092
    external_links:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_CLUSTER: "true"
      BROKER_ID: 2
      LISTENERS: PLAINTEXT://kafka2:9092
      ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181