
version: '3.3'

services:

  bigdata-kafka1:
    container_name: bigdata-kafka1
    build:
      context: ./services/kafka/1.1
    image: yinfuyuan/kafka:1.1.0-alpine
    hostname: bigdata-kafka1
    external_links:
      - bigdata-zookeeper1
      - bigdata-zookeeper2
      - bigdata-zookeeper3
    environment:
      KAFKA_CLUSTER: "true"
      BROKER_ID: 1
      LISTENERS: PLAINTEXT://bigdata-kafka1:9092
      ADVERTISED_LISTENERS: PLAINTEXT://bigdata-kafka1:9092
      ZOOKEEPER_CONNECT: bigdata-zookeeper1:2181,bigdata-zookeeper2:2181,bigdata-zookeeper3:2181

  bigdata-kafka2:
    container_name: bigdata-kafka2
    build:
      context: ./services/kafka/1.1
    image: yinfuyuan/kafka:1.1.0-alpine
    hostname: bigdata-kafka2
    external_links:
      - bigdata-zookeeper1
      - bigdata-zookeeper2
      - bigdata-zookeeper3
    environment:
      KAFKA_CLUSTER: "true"
      BROKER_ID: 2
      LISTENERS: PLAINTEXT://bigdata-kafka2:9092
      ADVERTISED_LISTENERS: PLAINTEXT://bigdata-kafka2:9092
      ZOOKEEPER_CONNECT: bigdata-zookeeper1:2181,bigdata-zookeeper2:2181,bigdata-zookeeper3:2181