
version: '3.3'

services:

  bigdata-hive1:
    container_name: bigdata-hive1
    build:
      context: ./services/hive/2.3
    image: yinfuyuan/hive:2.3.3
    hostname: bigdata-hive1
    external_links:
      - bigdata-mysql1

  bigdata-hive2:
    container_name: bigdata-hive2
    build:
      context: ./services/hive/2.3
    image: yinfuyuan/hive:2.3.3
    hostname: bigdata-hive2
    external_links:
      - bigdata-mysql1

  bigdata-hive3:
    container_name: bigdata-hive3
    build:
      context: ./services/hive/2.3
    image: yinfuyuan/hive:2.3.3
    hostname: bigdata-hive3
    external_links:
      - bigdata-mysql1