
version: '3.3'

services:

  zookeeper1:
    container_name: zookeeper1
    image: zookeeper:3.4.12
    restart: always
    hostname: zookeeper1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper2:
    container_name: zookeeper2
    image: zookeeper:3.4.12
    restart: always
    hostname: zookeeper2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper3:
    container_name: zookeeper3
    image: zookeeper:3.4.12
    restart: always
    hostname: zookeeper3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=0.0.0.0:2888:3888

  kafka1:
    container_name: kafka1
    build:
      context: ./services/kafka
    image: yinfuyuan/kafka:1.1.0-alpine
    hostname: kafka1
    links:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      BROKER_ID: 1
      LISTENERS: kafka1:9092
      ADVERTISED_LISTENERS: kafka1:9092
      ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181

  kafka2:
    container_name: kafka2
    build:
      context: ./services/kafka
    image: yinfuyuan/kafka:1.1.0-alpine
    hostname: kafka2
    links:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      BROKER_ID: 2
      LISTENERS: kafka2:9092
      ADVERTISED_LISTENERS: kafka2:9092
      ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
