
version: '3.3'

services:

  hadoop1:
    container_name: hadoop1
    build:
      context: ./services/hadoop/2.7
    image: yinfuyuan/hadoop:2.7.6
    hostname: hadoop1
    ports:
      - 50070:50070
      - 8088:8088